### ISSUE TITLE
middlewares is not iterable

### ISSUE THREAD

**Issue by victornswd** [OrJDev/prpc#42]
Hey! I wanted to test out pRPC and, while using SolidStart, I get this error:
```
middlewares is not iterable

PRPCClientError: middlewares is not iterable
    at Proxy.tryAndWrap (node_modules/@prpc/core/dist/index.js:80:11)
```
This error happens both in `create-prpc-app` and `create-jd-app`

**Comment by OrJDev** [comment]
Oh it looks like something within the rate limiter middleware, will take a look tomorrow but for now try avoiding upstash rate limit

**Comment by victornswd** [comment]
Great, thanks for looking into it. I played around with pRPC without the rate limiter middleware and it's a joy to use

**Comment by victornswd** [comment]
Hey, sorry to keep spamming this, but I found a weird workaround . Maybe it will help with debugging and figuring out what's the problem. 

Here's the workaround:
https://github.com/victornswd/middlewares-error/commit/32644cff6caded1e76da5fbcd341ba7e66182667

I've looked closer at the docs and tested out the `pipe$` example and that didn't cause the "middlewares is not iterable" error. So, by just wrapping the middleware in a pipe that just returns it I bypass the error

**Comment by OrJDev** [comment]
Hey there, this was fixed in https://github.com/OrJDev/prpc/commit/9c074777610aa8dfa06099b8930eed52444b5f14
could you confirm everything works on your end?

**Comment by OrJDev** [comment]
this was also updated in https://github.com/OrJDev/create-jd-app/releases/tag/v0.2.1

if you want to keep using create jd app

**Comment by victornswd** [comment]
Just tried with the update and everything works! Thanks!
