### ISSUE TITLE
Feature request: object-based arguments

### ISSUE THREAD

**Issue by Coretteket** [OrJDev/prpc#44]
From having played around with pRPC, today, this seems to be a super powerful library that's very easy to use – huge props! What is putting me off slightly is the interaction with the API, namely that you have to provide three (or more) arguments in a sequence. Personally, when it gets to three I like to [change my function into taking one object argument](https://www.justjeb.com/post/stop-using-function-parameters-now), instead. 

For this library specifically, I think it would be beneficial because it would allow to define the input types _before_ you write the query function, meaning you get type-safety when writing the function from scratch. 

From my testing, it seems writing my own wrapper to enable this is currently not supported (getting `TypeError: C:\Users\*\Documents\prpc-app\src\server\queries.ts: Cannot set properties of undefined (setting '0')`).

So, what I would like to propose is the alternative syntax below:

```ts
export const helloQuery = query$({
  key: 'hello',
  schema: z.object({ name: z.string() }),
  queryFn: ({ payload }) => {
    return `server says hello: ${payload.name}`;
  },
});
```

compared to the current syntax for reference:

```ts
export const helloQuery = query$(
  ({ payload }) => {
    return `server says hello: ${payload.name}`;
  },
  'hello',
  z.object({ name: z.string() })
);
```

Would love to hear your thoughts and discuss further! Do note that this does not _necessarily_ mean the current syntax would not be supported, as function overloads could enable this, I believe.

**Comment by OrJDev** [comment]
Writing helper functions for this library is almost impossible because of closures and babel transformations, so I don't think you will be able to implemented it yourself, however i can for sure add this as a function overload, will do it when I'm home and lyk (:

**Comment by OrJDev** [comment]
implemented in https://github.com/OrJDev/prpc/commit/4c85e03c77195ad86393d90fa58c358fd107a211

**Comment by Coretteket** [comment]
Awesome – can't believe how fast that was! 

I've been able to get the latest version working according to the new examples in the docs (`create-jd-app` with manually updated `@prpc/solid` and `@prpc/vite`). However, it appears the ordering of the object entries matters, which I think could be quite unexpected behaviour.

I can order the arguments in any way, _as long as the `queryFn` is first_. What I believe to be the great benefit of an object argument, allowing you write a schema before writing the function (ie. tRPC style-ish), does not seem to work. I then get the same error as when I write my own wrapper:

```
TypeError: C:\Users\***\Documents\jd-app\src\server\queries.ts: Cannot set properties of undefined (setting '0')
    at PluginPass.CallExpression (file:///C:/Users/***/Documents/jd-app/node_modules/.pnpm/@prpc+vite@0.3.14_vite@4.2.1/node_modules/@prpc/vite/dist/esm/production/index.mjs:1:1738)
    at newFn (C:\Users\***\Documents\jd-app\node_modules\.pnpm\@babel+traverse@7.21.4\node_modules\@babel\traverse\lib\visitors.js:149:21)
    at NodePath._call (C:\Users\***\Documents\jd-app\node_modules\.pnpm\@babel+traverse@7.21.4\node_modules\@babel\traverse\lib\path\context.js:45:20)
    ...
```

Is this a limitation of this approach?

**Comment by OrJDev** [comment]
> Awesome – can't believe how fast that was! 
> 
> 
> 
> I've been able to get the latest version working according to the new examples in the docs (`create-jd-app` with manually updated `@prpc/solid` and `@prpc/vite`). However, it appears the ordering of the object entries matters, which I think could be quite unexpected behaviour.
> 
> 
> 
> I can order the arguments in any way, _as long as the `queryFn` is first_. What I believe to be the great benefit of an object argument, allowing you write a schema before writing the function (ie. tRPC style-ish), does not seem to work. I then get the same error as when I write my own wrapper:
> 
> 
> 
> ```
> 
> TypeError: C:\Users\***\Documents\jd-app\src\server\queries.ts: Cannot set properties of undefined (setting '0')
> 
>     at PluginPass.CallExpression (file:///C:/Users/***/Documents/jd-app/node_modules/.pnpm/@prpc+vite@0.3.14_vite@4.2.1/node_modules/@prpc/vite/dist/esm/production/index.mjs:1:1738)
> 
>     at newFn (C:\Users\***\Documents\jd-app\node_modules\.pnpm\@babel+traverse@7.21.4\node_modules\@babel\traverse\lib\visitors.js:149:21)
> 
>     at NodePath._call (C:\Users\***\Documents\jd-app\node_modules\.pnpm\@babel+traverse@7.21.4\node_modules\@babel\traverse\lib\path\context.js:45:20)
> 
>     ...
> 
> ```
> 
> 
> 
> Is this a limitation of this approach? 

In what way is the order matter? The type safe way or the way the entire logic works? Could you provide some examples for it?

**Comment by OrJDev** [comment]
Closing for now, reopen if you have any issue or want anything to be added.

**Comment by zakybilfagih** [comment]
> Awesome – can't believe how fast that was!
> 
> I've been able to get the latest version working according to the new examples in the docs (`create-jd-app` with manually updated `@prpc/solid` and `@prpc/vite`). However, it appears the ordering of the object entries matters, which I think could be quite unexpected behaviour.
> 
> I can order the arguments in any way, _as long as the `queryFn` is first_. What I believe to be the great benefit of an object argument, allowing you write a schema before writing the function (ie. tRPC style-ish), does not seem to work. I then get the same error as when I write my own wrapper:
> 
> ```
> TypeError: C:\Users\***\Documents\jd-app\src\server\queries.ts: Cannot set properties of undefined (setting '0')
>     at PluginPass.CallExpression (file:///C:/Users/***/Documents/jd-app/node_modules/.pnpm/@prpc+vite@0.3.14_vite@4.2.1/node_modules/@prpc/vite/dist/esm/production/index.mjs:1:1738)
>     at newFn (C:\Users\***\Documents\jd-app\node_modules\.pnpm\@babel+traverse@7.21.4\node_modules\@babel\traverse\lib\visitors.js:149:21)
>     at NodePath._call (C:\Users\***\Documents\jd-app\node_modules\.pnpm\@babel+traverse@7.21.4\node_modules\@babel\traverse\lib\path\context.js:45:20)
>     ...
> ```
> 
> Is this a limitation of this approach?

Found the culprit, `props.key.name` should be compared to `isQuery ? 'queryFn' : 'mutationFn'` rather than `isQuery`
https://github.com/OrJDev/prpc/blob/f8823886d41c832e1c59ba9c0a345e1845f5f872/packages/vite/src/babel.ts#L98

Will create a PR to fix this. cc: @OrJDev

**Comment by OrJDev** [comment]
> > Awesome – can't believe how fast that was!
> 
> > 
> 
> > I've been able to get the latest version working according to the new examples in the docs (`create-jd-app` with manually updated `@prpc/solid` and `@prpc/vite`). However, it appears the ordering of the object entries matters, which I think could be quite unexpected behaviour.
> 
> > 
> 
> > I can order the arguments in any way, _as long as the `queryFn` is first_. What I believe to be the great benefit of an object argument, allowing you write a schema before writing the function (ie. tRPC style-ish), does not seem to work. I then get the same error as when I write my own wrapper:
> 
> > 
> 
> > ```
> 
> > TypeError: C:\Users\***\Documents\jd-app\src\server\queries.ts: Cannot set properties of undefined (setting '0')
> 
> >     at PluginPass.CallExpression (file:///C:/Users/***/Documents/jd-app/node_modules/.pnpm/@prpc+vite@0.3.14_vite@4.2.1/node_modules/@prpc/vite/dist/esm/production/index.mjs:1:1738)
> 
> >     at newFn (C:\Users\***\Documents\jd-app\node_modules\.pnpm\@babel+traverse@7.21.4\node_modules\@babel\traverse\lib\visitors.js:149:21)
> 
> >     at NodePath._call (C:\Users\***\Documents\jd-app\node_modules\.pnpm\@babel+traverse@7.21.4\node_modules\@babel\traverse\lib\path\context.js:45:20)
> 
> >     ...
> 
> > ```
> 
> > 
> 
> > Is this a limitation of this approach?
> 
> 
> 
> Found the culprit, `props.key.name` should be compared to `isQuery ? 'queryFn' : 'mutationFn'` rather than `isQuery`
> 
> https://github.com/OrJDev/prpc/blob/f8823886d41c832e1c59ba9c0a345e1845f5f872/packages/vite/src/babel.ts#L98
> 
> 
> 
> Will create a PR to fix this. cc: @OrJDev 

This was merged, can't believe I didn't notice it, can you upgrade prpc to its latest versions and lmk if it has been fixed?

**Comment by zakybilfagih** [comment]
> 

Upgraded my create-jd-app + prpc app and work like a charm!

**Comment by zakybilfagih** [comment]
> > > Awesome – can't believe how fast that was!
> > 
> > 
> > > 
> > 
> > 
> > > I've been able to get the latest version working according to the new examples in the docs (`create-jd-app` with manually updated `@prpc/solid` and `@prpc/vite`). However, it appears the ordering of the object entries matters, which I think could be quite unexpected behaviour.
> > 
> > 
> > > 
> > 
> > 
> > > I can order the arguments in any way, _as long as the `queryFn` is first_. What I believe to be the great benefit of an object argument, allowing you write a schema before writing the function (ie. tRPC style-ish), does not seem to work. I then get the same error as when I write my own wrapper:
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > TypeError: C:\Users***\Documents\jd-app\src\server\queries.ts: Cannot set properties of undefined (setting '0')
> > 
> > 
> > > ```
> > > at PluginPass.CallExpression (file:///C:/Users/***/Documents/jd-app/node_modules/.pnpm/@prpc+vite@0.3.14_vite@4.2.1/node_modules/@prpc/vite/dist/esm/production/index.mjs:1:1738)
> > > ```
> > 
> > 
> > > ```
> > > at newFn (C:\Users\***\Documents\jd-app\node_modules\.pnpm\@babel+traverse@7.21.4\node_modules\@babel\traverse\lib\visitors.js:149:21)
> > > ```
> > 
> > 
> > > ```
> > > at NodePath._call (C:\Users\***\Documents\jd-app\node_modules\.pnpm\@babel+traverse@7.21.4\node_modules\@babel\traverse\lib\path\context.js:45:20)
> > > ```
> > 
> > 
> > > ```
> > > ...
> > > ```
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > Is this a limitation of this approach?
> > 
> > 
> > Found the culprit, `props.key.name` should be compared to `isQuery ? 'queryFn' : 'mutationFn'` rather than `isQuery`
> > https://github.com/OrJDev/prpc/blob/f8823886d41c832e1c59ba9c0a345e1845f5f872/packages/vite/src/babel.ts#L98
> > 
> > Will create a PR to fix this. cc: @OrJDev
> 
> This was merged, can't believe I didn't notice it, can you upgrade prpc to its latest versions and lmk if it has been fixed?

Upgraded my create-jd-app + prpc app and work like a charm!
