### ISSUE TITLE
How to implement authentication and usage with drizzle orm and react native?

### ISSUE THREAD

**Issue by CherphAlt** [OrJDev/prpc#52]
How can I use something like supertokens to implement authentication and if yes then how also how can I use this with drizzle orm .how to use this with react native

**Comment by OrJDev** [comment]
> > How can I use something like supertokens to implement authentication and if yes then how also how can I use this with drizzle orm
> 
> pRPC has methods like "response$" and "error$" which allows you to return custom headers / cookies, etc. you can simply connect to your db from a function, here is an example:
> 
> ```ts
> const signIn = mutation$({
> key: "signIn",
> mutationFn: async ({ payload }) => {
> const user = await db.getUser(payload.email)
> // logic here ...
> if(!user) {
> return error$("no such user");
> } 
> // more logic
> return response$(myUser, { headers: ... })
> },
> schema: z.object({ email: z.string() })
> })
> ```

Another example for it is create jd app which uses prpc middlewares to get logged in user from the authjs api

https://github.com/orjdev/create-jd-app

**Comment by OrJDev** [comment]
Oh I didn't notice you were asking about react native, the cool thing about solidstart's server$ is that you can access it via an http request, so this api is public and you could access it from your react native app using axios

**Comment by CherphAlt** [comment]
> Oh I didn't notice you were asking about react native, the cool thing about solidstart's server$ is that you can access it via an http request, so this api is public and you could access it from your react native app using axios

Ok but what route do i have to make the request like is the variable name?
