### ISSUE TITLE
Websockets?

### ISSUE THREAD

**Issue by CherphAlt** [OrJDev/prpc#57]

**Comment by OrJDev** [comment]
In what adapter would you like to implement websockets? Nextjs? Solidstart?

**Comment by CherphAlt** [comment]
> In what adapter would you like to implement websockets? Nextjs? Solidstart?

SolidStart

**Comment by OrJDev** [comment]
> > In what adapter would you like to implement websockets? Nextjs? Solidstart?
> 
> 
> 
> SolidStart

Oh basically queryFn / mutationFn are both functions wrapped with `server$` so you can implement a socket / stream there like you would do in normal server function, im not sure how it is in written code maybe its best to ask in the SolidStart repo for a better answer

**Comment by OrJDev** [comment]
Actually I'm thinking of implementing some subscription$ function that will enable websockets, will update you in here

**Comment by OrJDev** [comment]
Moved this to https://github.com/OrJDev/prpc/issues/68
