### ISSUE TITLE
query$ cache

### ISSUE THREAD

**Issue by advancedtw** [OrJDev/prpc#69]
how are we supposed to handle caching ? I was under the impression that @tanstack/solid-query would do the caching but the server query seems to always be run even with the same arguments.

**Comment by OrJDev** [comment]
You can return a response with caching headers, this can be cached as your will.

```ts
return response$(myData, { headers: {...} });
```

**Comment by advancedtw** [comment]
somthing like that right? 
```ts
const adder = query$({
        queryFn: async ({ payload }) => {
                const result = payload.a + payload.b;
                return response$(result, {
                        headers: {
                                "Cache-Control": "public, max-age=604800",
                        },
                });
        },
        key: "adding",
        schema: z.object({
                a: z.number().max(5),
                b: z.number().max(10),
        }),
});
```
i'm still hitting the server on signal change. am i missing something obvious?

**Comment by OrJDev** [comment]
yep exactly, response$ is basically just a way to return an actual web api response, you can send any header you wish, in this case cache control should work.

```ts
const ONE_DAY_IN_SECONDS = 60 * 60 * 24;
return response$(Math.sqrt(70), {
 headers: {
        'cache-control': `s-maxage=1, stale-while-revalidate=${ONE_DAY_IN_SECONDS}`,
      },
});
```

**Comment by advancedtw** [comment]
still the same I have tried other cache control settings but it's still getting called. the request headers are set as expected which is good but the browser doesn't seem to care. could it be because the method is POST instead of GET? 
have you managed to make it work on your side ?

**Comment by OrJDev** [comment]
It should be, will try it out and lyk

**Comment by advancedtw** [comment]
ok thanks for the support. I will try a few things on my side before opening a issue.
