### ISSUE TITLE
Feature request: normalizing HTTP methods

### ISSUE THREAD

**Issue by Coretteket** [OrJDev/prpc#73]
It seems that regardless of whether pRPC is doing a `query$` or `mutation$` the actual HTTP request will be a POST request. This mostly works fine, but has become a bit of an issue trying to work with Vercel's server-side caching, [as it refuses to cache POST requests](https://vercel.com/docs/concepts/edge-network/caching#cacheable-response-criteria). This is quite understandable considering the semantics of HTTP methods, so I would love to see pRPC more closely follow these semantics. I would think GETting queries and POSTing mutations would make the most sense, but I'm eager to hear your thoughts. (If this would be too breaking of a change, a 'method' option on a query would also work.) 

I understand that pRPC uses Solid Start's `server$` under the hood (for my use-case), so please do let me know if this is not possible for pRPC as it stands.

**Comment by OrJDev** [comment]
> It seems that regardless of whether pRPC is doing a `query$` or `mutation$` the actual HTTP request will be a POST request. This mostly works fine, but has become a bit of an issue trying to work with Vercel's server-side caching, [as it refuses to cache POST requests](https://vercel.com/docs/concepts/edge-network/caching#cacheable-response-criteria). This is quite understandable considering the semantics of HTTP methods, so I would love to see pRPC more closely follow these semantics. I would think GETting queries and POSTing mutations would make the most sense, but I'm eager to hear your thoughts. (If this would be too breaking of a change, a 'method' option on a query would also work.) 
> 
> 
> 
> I understand that pRPC uses Solid Start's `server$` under the hood (for my use-case), so please do let me know if this is not possible for pRPC as it stands. 

It is not possible for solid-prpc in its current implementation as it is using server$ under the hood as you said, however for other frameworks like nextjs this is possible since thaler allows such things (get$, etc). This should be possible for solid if we decide to use thaler in solid as-well, it just requires additional npm packages and api handler.

**Comment by Coretteket** [comment]
That's what I was afraid of. I might open an issue on SolidStart then. Huge thanks for the quick response, anyways!

**Comment by OrJDev** [comment]
moved to solid-start
