### ISSUE TITLE
Defining types in mutation$

### ISSUE THREAD

**Issue by aquarazorda** [OrJDev/prpc#77]
It's impossible to define mutationFn's input and output types, whenever you are not using schema in options.

**Comment by OrJDev** [comment]
> It's impossible to define mutationFn's input and output types, whenever you are not using schema in options.

That is because we want to make sure the data that's passed to the function is correct, therefore when expecting an input in a mutation fn please use the schema option and mention a zod schema that will be used to validate the input, this isn't an issue it's intended to be this way

**Comment by aquarazorda** [comment]
Why shouldn't it be possible to have type defined for the payload, without providing schema? Then schema should be required?

**Comment by OrJDev** [comment]
> > > It's impossible to define mutationFn's input and output types, whenever you are not using schema in options.
> 
> > 
> 
> > That is because we want to make sure the data that's passed to the function is correct, therefore when expecting an input in a mutation fn please use the schema option and mention a zod schema that will be used to validate the input, this isn't an issue it's intended to be this way
> 
> 
> 
> Why shouldn't it be possible to have type defined for the payload, without providing schema? Then schema should be required?

The schema should be required in order to assure that the type of the payload passed to the function is the actual expected payload, that's when you decide to use zod schemas to validate data and type your input around it
