### ISSUE TITLE
Function argument spread shouldn't be required

### ISSUE THREAD

**Issue by aquarazorda** [OrJDev/prpc#78]
So whenever you're using query$ or mutation$, you always need to spread the function arguments and return the data inside curly braces, otherwise app crashes.

**Comment by OrJDev** [comment]
> So whenever you're using query$ or mutation$, you always need to spread the function arguments and return the data inside curly braces, otherwise app crashes.

Yes that is because of the babel plugin that is currently written, its expecting specific variables, this can be improved to work with a single variable but yes currently this is the situation

**Comment by OrJDev** [comment]
planned on later, not urgent, prpc has certain syntax that must be followed
